// Repos
export const REPOS_ADD = 'REPOS_ADD'
export const REPOS_SET = 'REPOS_SET'
export const REPOS_SET_LOADING = 'REPOS_SET_LOADING'
export const REPOS_SET_ERROR = 'REPOS_SET_ERROR'
export const REPOS_SET_SELECTED_DATE = 'REPOS_SET_SELECTED_DATE'
export const REPOS_SET_SELECTED_LANGUAGES = 'REPOS_SET_SELECTED_LANGUAGES'

// Stars
export const STARS_SET = 'STARS_SET'
export const STARS_ADD = 'STARS_ADD'
export const STARS_REMOVE = 'STARS_REMOVE'
export const STARS_SET_INFOS = 'STARS_SET_INFOS'
export const STARS_ADD_INFO = 'STARS_ADD_INFO'
export const STARS_REMOVE_INFO = 'STARS_REMOVE_INFO'
export const STARS_SET_LOADING = 'STARS_SET_LOADING'
export const STARS_SET_ERROR = 'STARS_SET_ERROR'
